#!/usr/bin/env bash

protected_branches=('master' 'develop')
# protected_branch='master'  
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

protected_branch=''
for i in ${protected_branches[@]}; do
  if [ "$i" = "$current_branch" ]; then
    protected_branch=$i
    break
  fi
done

if [ "${#protected_branch}" -gt "0" ]; then
  read -p "You're about to push $protected_branch, is that what you intended? [y|n] " -n 1 -r < /dev/tty
  echo
  if echo $REPLY | grep -E '^[Yy]$' > /dev/null; then
    exit 0 # push will execute
  fi
  exit 1 # push will not execute
else  
  exit 0 # push will execute
fi  
