# -*- mode: ruby -*-
# vi: set ft=ruby :

NODES = 1
MEMORY = 2048
CPUS = 1

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = true
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "~/Projects/sari-sari-store", "/home/vagrant/sari-sari-store", type: "rsync",
    rsync__exclude: [
      ".git/",
      ".ropeproject/",
      ".idea/",
      ".tox/",
      "*.egg-info",
      "vagrant"
    ]

  config.vm.provider "virtualbox" do |vb|
    vb.name = "my-dev-box1"
    vb.memory = MEMORY
    vb.cpus = CPUS
  end

  config.vm.provision :docker
  config.vm.provision :docker_compose,
    run: "always",
    compose_version: "1.6.0"
  config.vm.provision :shell,
    path: "bootstrap.sh"

  config.gatling.rsync_on_startup = false
end
