# -*- mode: ruby -*-
# vi: set ft=ruby :

NODES = 1
MEMORY = 2048
CPUS = 1

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = true
  config.vm.hostname = "my-dev-box-1"
  config.vm.network "private_network", ip: "14.14.33.10"
  config.vm.synced_folder "~/.ssh", "/home/vagrant/.ssh"
  config.vm.synced_folder "~/.aws", "/home/vagrant/.aws"
  config.vm.synced_folder "~/Projects", "/home/vagrant/Projects", type: "rsync",
    rsync__exclude: [
      ".git/",
      ".ropeproject/",
      ".idea/",
      ".tox/",
      "*.egg-info",
      "node_modules",
      "aws",
      "vagrant"
    ]

  config.vm.provider "virtualbox" do |vb|
    vb.name = "my-dev-box-1"
    vb.memory = MEMORY
    vb.cpus = CPUS
  end

  config.vm.provision :docker
  config.vm.provision :docker_compose,
    run: "always",
    compose_version: "1.8.0"
  config.vm.provision :shell,
    path: "bootstrap.sh"

  config.gatling.rsync_on_startup = false
end
